huyvd/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('users', 'UsersContronller');

huyvd/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable = [
        'name', 'email', 'password', 'mail_address',
    ];
    protected $hidden = [
        'password', 'remember_token',
    ];
}

huyvd/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

huyvd/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

huyvd/app/Http/Controllers/UsersContronller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CreateUserRequest;
use App\Models\User;

class UsersContronller extends Controller
{
    public function index()
    {
        $users = User::orderBy('mail_address', 'ASC')->paginate(20);
        return view('user.index',['user'=>$users]);
    }
    public function store(CreateUserRequest $Request)
    {
        $users = $Request->All();
        $users['password'] = bcrypt($Request->password);
        User::create($users);
        $Request->session()->flash('status', 'Thêm người dùng thành công!');
        return redirect()->route('users.create');
    }
    public function create()
    {
        return view('user.add');
    }
}

huyvd/resources/views/user/add.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Add user</title>
    <link href="{{ url('twbs/bootstrap/dist/css/bootstrap.min.css')}}" style="text/css" rel="stylesheet">
</head>
<body>
    <div class="container">
    <h1 class="well">Registration Form</h1>
        <form method="POST" action="{{ route('users.store') }}">
            {{csrf_field()}}
            @if (session('status'))
                <div class="alert alert-info">{{session('status')}}</div>
            @endif
            {{-- @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif --}}
            <div class="form-group">
                <label for="exampleInputEmail1" style="@if($errors->has('name')) {{'color: red;'}} @endif">Tên</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Tên" name="name" style="@if($errors->has('name')) {{'border: solid 1px red;'}} @endif">
                @if($errors->has('mail_address'))
                   <p style="color: red">{{ $errors->first('name') }}</p>
                @endif
            </div>
            <div class="form-group ">
                <label for="exampleInputEmail1" style="@if($errors->has('mail_address')) {{'color: red;'}} @endif">Email address</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="mail_address" style="@if($errors->has('mail_address')) {{'border: solid 1px red;'}} @endif">
                @if($errors->has('mail_address'))
                   <p style="color: red">{{ $errors->first('mail_address') }}</p>
                @endif
            </div>
            <div class="form-group">
                <label style="@if($errors->has('address')) {{'color: red;'}} @endif">Address</label>
                <textarea placeholder="Enter Address Here.." rows="3" class="form-control" name="address" style="@if($errors->has('address')) {{'border: solid 1px red;'}} @endif"></textarea>
                @if($errors->has('mail_address'))
                   <p style="color: red">{{ $errors->first('address') }}</p>
                @endif
            </div>
            <div class="form-group">
                <label style="@if($errors->has('phone')) {{'color: red;'}} @endif">Phone Number</label>
                <input type="text" placeholder="Enter Phone Number Here.." class="form-control" name="phone" style="@if($errors->has('phone')) {{'border: solid 1px red;'}} @endif">
                @if($errors->has('mail_address'))
                   <p style="color: red">{{ $errors->first('phone') }}</p>
                @endif
            </div>
            <div class="form-group">
                <label style="@if($errors->has('password')) {{'color: red;'}} @endif">Password</label>
                <input type="password" placeholder="Enter Password Here.." class="form-control" name="password" style="@if($errors->has('password')) {{'border: solid 1px red;'}} @endif">
                @if($errors->has('mail_address'))
                   <p style="color: red">{{ $errors->first('password') }}</p>
                @endif
            </div>
            <div class="form-group">
                <label style="@if($errors->has('password_confirmation')) {{'color: red;'}} @endif">Password confirm</label>
                <input type="password" placeholder="Enter Password Here.." class="form-control" name="password_confirmation" style="@if($errors->has('password_confirmation')) {{'border: solid 1px red;'}} @endif">
                @if($errors->has('mail_address'))
                   <p style="color: red">{{ $errors->first('password_confirmation') }}</p>
                @endif
            </div>
            <input type="submit" class="btn btn-lg btn-info" value="Thêm mới"></input>
        </form> 
</body>
</html>

huyvd/resources/views/user/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Danh sách</title>
    <link href="{{ url('twbs/bootstrap/dist/css/bootstrap.min.css')}}" style="text/css" rel="stylesheet">
    <style type="text/css">
        .example{
            margin: 20px;
        }
    </style>
</head>
<body>
    <div class="example">
        <div class="container">
            <div class="row">
                <h2>Danh sách</h2>
                <table class="table table-bordered">
                    <thead>
                        <tr style="text-align: center;">
                            <th>STT</th>
                            <th>Tên</th>
                            <th>Địa chỉ email</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                        </tr>
                    </thead>
                    <tbody>
                        <<?php $stt=1; ?>
                        @foreach($user as $value)
                        <tr>
                            <td>{{$stt++}}</td>
                            <td>{{$value->name}}</td>
                            <td>{{$value->mail_address}}</td>
                            <td>{{$value->address}}</td>
                            <td>{{$value->phone}}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <a href="{{route('users.create') }}" class="btn btn-lg btn-info">Thêm user</a>
            </div >
        </div>
    </div>
    {{ $user->links()}}
</body>
</html>